server {
    listen 80;
    server_name sa7a7ly.online www.sa7a7ly.online;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name sa7a7ly.online www.sa7a7ly.online;

    ssl_certificate /etc/letsencrypt/live/sa7a7ly.online/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sa7a7ly.online/privkey.pem;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }
}
