server {
    listen 80;
    server_name sa7a7ly.online www.sa7a7ly.online;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name sa7a7ly.online www.sa7a7ly.online;

    ssl_certificate /etc/letsencrypt/live/sa7a7ly.online/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sa7a7ly.online/privkey.pem;

    # FRONTEND (Docker on 3001)
    location / {
        proxy_pass http://localhost:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # BACKEND (Docker on 5000)
    location /api {
        proxy_pass http://localhost:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
