version: "3.8"

services:

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    volumes:
      - ./uploads:/app/uploads

  worker:
    build: ./backend
    command: node workers/gradingWorker.js
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    volumes:
      - ./uploads:/app/uploads

  redis:
    image: redis:7-alpine